[package]
name = "leprechaun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
dotenvs = "0.1.0"
polars = "0.34.2"
ratatui = "0.24.0"
reqwest = "0.11.22"
