[package]
name = "leprechaun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
dialoguer = "0.11.0"
dotenvs = "0.1.0"
polars = "0.34.2"
reqwest = "0.11.22"
log = "0.4"